name: build-and-deploy
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.3'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      # - run: pnpm postbuild
      - run: pnpm dlx wrangler pages deploy dist --project-name=blog-leo
        if: github.event_name != 'pull_request' && github.event_name != 'merge_group'
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
